bag/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.view_bag, name='view_bag'),
    path('add/<item_id>/', views.add_to_bag, name='add_to_bag'),
    path('adjust/<item_id>/', views.adjust_bag, name='adjust_bag'),
    path('remove/<item_id>/', views.remove_from_bag, name='remove_from_bag'),
]

mpt_gym/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('clubs/', include('clubs.urls')),
    path('products/', include('products.urls')),
    path('bag/', include('bag.urls')),
    path('checkout/', include('checkout.urls')),
    path('profile/', include('profiles.urls')),
    path('contact/', include('contact.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.all_products, name='products'),
    path('<int:product_id>/', views.product_detail, name='product_detail'),
    path('add/', views.add_product, name='add_product'),
    path('edit/<int:product_id>/', views.edit_product, name='edit_product'),
    path('delete/<int:product_id>/', views.delete_product,
         name='delete_product'),
    path('add_review/<int:product_id>/', views.add_review,
         name='add_review'),
    path('delete_review/<int:review_id>/', views.delete_review,
         name='delete_review'),
]

checkout/models.py
import uuid

from django.db import models
from django.db.models import Sum
from django.conf import settings

from django_countries.fields import CountryField

from products.models import Product
from profiles.models import UserProfile


class Order(models.Model):
    order_number = models.CharField(
        max_length=32, null=False, editable=False)
    user_profile = models.ForeignKey(
        UserProfile, on_delete=models.SET_NULL,
        null=True, blank=True, related_name='orders')
    full_name = models.CharField(max_length=50, null=False, blank=False)
    email = models.EmailField(max_length=254, null=False, blank=False)
    phone_number = models.CharField(max_length=20, null=False, blank=False)
    country = CountryField(blank_label='Country *', null=False, blank=False)
    postcode = models.CharField(max_length=20, null=True, blank=True)
    town_or_city = models.CharField(
        max_length=40, null=False, blank=False)
    street_address1 = models.CharField(
        max_length=80, null=False, blank=False)
    street_address2 = models.CharField(
        max_length=80, null=True, blank=True)
    county = models.CharField(max_length=80, null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True)
    delivery_cost = models.DecimalField(
        max_digits=6, decimal_places=2, null=False, default=0)
    order_total = models.DecimalField(
        max_digits=10, decimal_places=2, null=False, default=0)
    grand_total = models.DecimalField(
        max_digits=10, decimal_places=2, null=False, default=0)
    original_bag = models.TextField(null=False, blank=False, default='')
    stripe_pid = models.CharField(
        max_length=254, null=False, blank=False, default='')

    def _generate_order_number(self):
        """
        Generate a random, unique order number using UUID
        """
        return uuid.uuid4().hex.upper()

    def update_total(self):
        """
        Update grand total each time a line item is added,
        accounting for delivery costs.
        """
        self.order_total = self.lineitems.aggregate(Sum(
            'lineitem_total'))['lineitem_total__sum'] or 0
        if self.order_total < settings.FREE_DELIVERY_THRESHOLD:
            self.delivery_cost = self.order_total * settings.STANDARD_DELIVERY_PERCENTAGE / 100
        else:
            self.delivery_cost = 0
        self.grand_total = self.order_total + self.delivery_cost
        self.save()

    def save(self, *args, **kwargs):
        """
        Override the original save method to set the order number
        if it hasn't been set already.
        """
        if not self.order_number:
            self.order_number = self._generate_order_number()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.order_number


class OrderLineItem(models.Model):
    order = models.ForeignKey(
        Order, null=False, blank=False,
        on_delete=models.CASCADE, related_name='lineitems')
    product = models.ForeignKey(
        Product, null=False, blank=False, on_delete=models.CASCADE)
    product_size = models.CharField(
        max_length=2, null=True, blank=True)  # XS, S, M, L, XL
    quantity = models.IntegerField(null=False, blank=False, default=0)
    lineitem_total = models.DecimalField(
        max_digits=6, decimal_places=2, null=False,
        blank=False, editable=False)

    def save(self, *args, **kwargs):
        """
        Override the original save method to set the lineitem total
        and update the order total.
        """
        self.lineitem_total = self.product.price * self.quantity
        super().save(*args, **kwargs)

    def __str__(self):
        return f'SKU {self.product.sku} on order {self.order.order_number}'

products/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Category(models.Model):

    class Meta:
        verbose_name_plural = 'Categories'

    name = models.CharField(max_length=254)
    friendly_name = models.CharField(max_length=254, null=True, blank=True)

    def __str__(self):
        return self.name

    def get_friendly_name(self):
        return self.friendly_name


class Product(models.Model):
    category = models.ForeignKey('Category', null=True, blank=True,
                                 on_delete=models.SET_NULL)
    sku = models.CharField(max_length=254, null=True, blank=True)
    name = models.CharField(max_length=254)
    description = models.TextField()
    has_sizes = models.BooleanField(default=False, null=True, blank=True)
    price = models.DecimalField(max_digits=8, decimal_places=2)
    rating = models.DecimalField(max_digits=6, decimal_places=2,
                                 null=True, blank=True)
    flavour = models.CharField(max_length=150, null=True, blank=True)
    weight = models.CharField(max_length=20, null=True, blank=True)
    image_url = models.URLField(max_length=1024, null=True, blank=True)
    image = models.ImageField(null=True, blank=True)
    tags = models.ManyToManyField('Tag', blank=True)
    ingredients = models.TextField(null=True, blank=True)
    number_of_sessions = models.IntegerField(null=True, blank=True)
    price_per_session = models.DecimalField(max_digits=6, decimal_places=2,
                                            null=True, blank=True)

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=200)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class ProductReview(models.Model):
    """
    Product Review Model
    """
    product = models.ForeignKey(Product, related_name='reviews', null=True,
                                blank=True, on_delete=models.SET_NULL)
    user = models.ForeignKey(User, null=True, blank=True,
                             on_delete=models.CASCADE)
    comment = models.TextField()
    review_rating = models.IntegerField(default=0)
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.id)

products/forms.py
from django import forms
from .widgets import CustomClearableFileInput
from .models import Product, Category, ProductReview


class ProductForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = '__all__'

    image = forms.ImageField(label='Image', required=False,
                             widget=CustomClearableFileInput)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        categories = Category.objects.all()
        friendly_names = [(c.id, c.get_friendly_name()) for c in categories]

        self.fields['category'].choices = friendly_names
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'border-black rounded-0'


class ProductReviewForm(forms.ModelForm):

    class Meta:
        model = ProductReview
        fields = ('comment', 'review_rating',)

    def __init__(self, *args, **kwargs):
        """
        Add placeholders and classes, remove auto-generated
        labels and set autofocus on first field
        """
        super().__init__(*args, **kwargs)

products/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.db.models.functions import Lower
from .models import Product, Category, ProductReview
from .forms import ProductReviewForm

from .forms import ProductForm


# Create your views here.
def all_products(request):
    """
    To return a view to the different services.
    """

    categories = Category.objects.all()
    products = Product.objects.all()
    query = None
    categories = None
    sort = None
    direction = None

    if request.GET:
        if 'sort' in request.GET:
            sortkey = request.GET['sort']
            sort = sortkey
            if sortkey == 'name':
                sortkey = 'lower_name'
                products = products.annotate(lower_name=Lower('name'))
            if sortkey == 'category':
                sortkey = 'category__name'
            if 'direction' in request.GET:
                direction = request.GET['direction']
                if direction == 'desc':
                    sortkey = f'-{sortkey}'
            products = products.order_by(sortkey)

    if request.GET:
        if 'category' in request.GET:
            categories = request.GET['category'].split(',')
            products = products.filter(category__name__in=categories)
            categories = Category.objects.filter(name__in=categories)

        if 'q' in request.GET:
            query = request.GET['q']
            if not query:
                messages.error(request, "Please enter any search criteria!")
                return redirect(reverse('products'))

            queries = Q(name__icontains=query) | Q(description__icontains=query)
            products = products.filter(queries)

    current_sorting = f'{sort}_{direction}'

    context = {
        'products': products,
        'categories': categories,
        'search_term': query,
        'current_categories': categories,
        'current_sorting': current_sorting,
    }
    return render(request, 'products/products.html', context)


def product_detail(request, product_id):
    """
    To return a view to see a single service details.
    """

    product = get_object_or_404(Product, pk=product_id)
    # for the product review rating post
    form = ProductReviewForm()

    context = {
        'product': product,
        'form': form,
    }
    return render(request, 'products/product_detail.html', context)


@login_required
def add_product(request):
    """
    Add a product to the store
    """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry only Gym Owner can do this.')
        return redirect(reverse('home'))

    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save()
            messages.success(request, 'Successfully added product!')
            return redirect(reverse('product_detail', args=[product.id]))
        else:
            messages.error(request, 'Faild to add product. \
                 Please ensure the form is valid.')
    else:
        form = ProductForm()

    template = 'products/add_product.html'
    context = {
        'form': form,
    }

    return render(request, template, context)


@login_required
def edit_product(request, product_id):
    """
    Edit a product in the store
    """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry only Gym Owner can do this.')
        return redirect(reverse('home'))

    product = get_object_or_404(Product, pk=product_id)

    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            messages.success(request, 'Successfully updated product!')
            return redirect(reverse('product_detail', args=[product.id]))
        else:
            messages.error(request, 'Failed to update product. \
                Please ensure the form is vaild.')
    else:
        form = ProductForm(instance=product)
        messages.info(request, f'You are editing {product.name}')

    template = 'products/edit_product.html'
    context = {
        'form': form,
        'product': product,
    }

    return render(request, template, context)


@login_required
def delete_product(request, product_id):
    """
    Delete a product from the store.
    """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry only Gym Owner can do this.')
        return redirect(reverse('home'))

    product = get_object_or_404(Product, pk=product_id)
    product.delete()
    messages.success(request, 'Product deleted!')
    return redirect(reverse('products'))


@login_required
def add_review(request, product_id):
    """ Allow users to add  a product review """

    product = get_object_or_404(Product, pk=product_id)

    # https://stackoverflow.com/questions/56982579/how-to-display-all-the-reviews-for-the-particular-product

    if request.user.is_authenticated:
        if request.method == 'POST':
            form = ProductReviewForm(request.POST)
            if form.is_valid():
                review = form.save(commit=False)
                review.product = product
                review.user = request.user
                review.save()
                messages.success(request, 'Your review \
                    has been successfully added!')
                return redirect(reverse('product_detail', args=[product.id]))
            else:
                messages.error(request, 'Something went wrong! \
                    Please try to add your review again.')
    context = {
        'form': form
    }
    return render(request, context)


@login_required
def delete_review(request, review_id):
    """ Delete review """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry,just site managment can do that.')
        return redirect(reverse('home'))
    elif request.user.is_superuser:
        # https://stackoverflow.com/questions/70024172/how-to-delete-model-by-filtering-with-pk
        review = ProductReview.objects.filter(pk=review_id).last()
        # need the product id
        product_id = review.product_id
        review.delete()
        messages.success(request, f"{ review.user }'s review '{ review.comment }' has been \
        removed!")
        return redirect(reverse('product_detail', args=[product_id]))

products/templates/products/add_product.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
<div class="container header-container">
    <div class="row">
        <div class="col"></div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="overlay"></div>
<div class="container">
    <div class="row">
        <div class="col-12 col-md-6">
            <hr>
            <h2 class="logo-font mb-4">Product Management</h2>
            <h5 class="text-muted">Add a Product</h5>
            <hr>
        </div>
    </div>
    <div class="row">
        <div class="col-12 col-md-6">
            <form method="POST" action="{% url 'add_product' %}" class="form mb-2" enctype="multipart/form-data">
                {% csrf_token %}
                {% for field in form %}
                {% if field.name != 'image' %}
                {{ field | as_crispy_field }}
                {% else %}
                {{ field }}
                {% endif %}
                {% endfor %}
                <div class="text-right">
                    <a class="btn btn-outline-black rounded-0" href="{% url 'products' %}">Cancel</a>
                    <button class="btn btn-black rounded-0" type="submit">Add Product</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

{% block postloadjs %}
{{ block.super }}
<script type="text/javascript">
    $('#new-image').change(function () {
        var file = $('#new-image')[0].files[0];
        $('#filename').text(`Image will be set to: ${file.name}`);
    });
</script>
{% endblock %}

products/templates/products/edit_product.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
<div class="container header-container">
    <div class="row">
        <div class="col"></div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="overlay"></div>
<div class="container">
    <div class="row">
        <div class="col-12 col-md-6">
            <hr>
            <h2 class="logo-font mb-4">Product Management</h2>
            <h5 class="text-muted">Edit a Product</h5>
            <hr>
        </div>
    </div>
    <div class="row">
        <div class="col-12 col-md-6">
            <form method="POST" action="{% url 'edit_product' product.id %}" class="form mb-2"
                enctype="multipart/form-data">
                {% csrf_token %}
                {% for field in form %}
                {% if field.name != 'image' %}
                {{ field | as_crispy_field }}
                {% else %}
                {{ field }}
                {% endif %}
                {% endfor %}
                <div class="text-right">
                    <a class="btn btn-outline-black rounded-0" href="{% url 'products' %}">Cancel</a>
                    <button class="btn btn-black rounded-0" type="submit">Update Product</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

{% block postloadjs %}
{{ block.super }}
<script type="text/javascript">
    $('#new-image').change(function () {
        var file = $('#new-image')[0].files[0];
        $('#filename').text(`Image will be set to: ${file.name}`);
    });
</script>
{% endblock %}

products/templates/products/product_detail.html
{% extends "base.html" %}
{% load static %}


{% block content %}

<div class="container-fluid">

    <div class="row">
        <!-- service col -->
        <div class="col">
            <div class="row">
                <div class="col text-center mt-3">
                    <h2 class="text-black text-uppercase">{{ product.name }}</h2>
                    <hr class="text-black">
                </div>
            </div>
            <!-- sidenav links tags -->
            <div class="row">
                <div class="col col-sm-8 col-12 mb-3 p-3 breadcrumb" style="--bs-breadcrumb-divider: '|';">
                    <p class="breadcrumb-item small p-1 "><a class="text-danger text-uppercase text-decoration-none"
                            href="{% url 'products' %}?category={{ product.category.name }}">
                            {{ product.category.friendly_name }}</a></p>
                    <p class="breadcrumb-item p-1 text-success small text-capitalize text-decoration-none active"
                        aria-current="page">{{ product.name }}</p>
                </div>
                <div class="col col-sm-4 col-12 mb-3 p-3">
                    {% if request.user.is_superuser %}
                    <small class="ml-3">
                        <span>Click here to </span>
                        <a href="{% url 'edit_product' product.id %}">Edit</a>
                        <span> /</span>
                        <a class="text-danger" href="{% url 'delete_product' product.id %}">Delete</a>
                        <span> this product!</span>
                    </small>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    <section class="row">
        <div class="col-12 col-md-6 col-lg-4 offset-lg-2">
            <div class="image-container my-5">
                {% if product.image %}
                <a href="{{ product.image.url }}" target="_blank">
                    <img class="card-img-top img-fluid" src="{{ product.image.url }}" alt="{{ product.name }}">
                </a>
                {% else %}
                <a href="">
                    <img class="card-img-top img-fluid" src="{{ MEDIA_URL }}noimage.png" alt="{{ product.name }}">
                </a>
                {% endif %}
                <div class="accordion mt-3" id="accordionExample">
                    <div class="accordion-item">
                        <h2 class="accordion-header" id="headingOne">
                            <button class="accordion-button" type="button" data-bs-toggle="collapse"
                                data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                                Description:
                            </button>
                        </h2>
                        <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne"
                            data-bs-parent="#accordionExample">
                            <div class="accordion-body">
                                <strong>{{ product.description}}</strong>
                            </div>
                        </div>
                    </div>
                    {% if product.ingredients%}
                    <div class="accordion-item mt-2">
                        <h2 class="accordion-header" id="headingTwo">
                            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                                data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                                Ingredients
                            </button>
                        </h2>
                        <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo"
                            data-bs-parent="#accordionExample">
                            <div class="accordion-body">
                                <strong>{{ product.ingredients}}</strong>
                            </div>
                        </div>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="col-12 col-md-6 col-lg-4">
            <div class="product-details-container mb-5 mt-md-5">
                <small>
                    <p class="mb-0 text-black">{{ product.sku }}</p>
                </small>
                <h4 class="text-uppercase">{{ product.name }}</h4>
                {% if product.category %}
                <p class="small mt-1 mb-0">
                    <a class="text-muted" href="{% url 'products' %}?category={{ product.category.name }}">
                        <i class="fas fa-tag mr-1 text-black"></i> {{ product.category.friendly_name }}
                    </a>
                </p>
                {% endif %}
                {% if product.rating %}
                <small class="text-muted"><i class="fas fa-star mr-1 text-black"></i>{{ product.rating }} / 5</small>
                {% else %}
                <small class="text-muted text-black">No Rating</small>
                {% endif %}
                <hr>
                <p class="lead mb-0 text-left font-weight-bold text-black">{{ product.price }} kr</p>
                <hr>
                {% if product.number_of_sessions %}
                <p class="lead mb-0 text-left font-weight-bold text-black">Package size:
                    {{ product.number_of_sessions }}</p>
                <p class="lead mb-0 text-left font-weight-bold text-black">{{ product.price_per_session }}kr of each
                    session</p>
                {% endif %}
                <form class="form" action="{% url 'add_to_bag' product.id %}" method="POST">
                    {% csrf_token %}
                    <div class="form-row">
                        {% with product.has_sizes as s %}
                        {% if s %}
                        <div class="col-12">
                            <p><strong class="text-black">Size:</strong></p>
                            <select class="form-control rounded-0 w-50 text-black" name="product_size"
                                id='id_product_size'>
                                <option value="xs">XS</option>
                                <option value="s">S</option>
                                <option value="m" selected>M</option>
                                <option value="l">L</option>
                                <option value="xl">XL</option>
                            </select>
                        </div>
                        {% endif %}
                        {% if product.weight %}
                        <h5 class="text-black"><strong>{{ product.weight }} kg</strong></h5>
                        {% endif %}
                        <div class="pt-3">
                            <hr>
                        </div>
                    </div>
                    <div class="col-12">
                        <p><strong>Quantity:</strong></p>
                        <div class="form-group w-50">
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <button class="decrement-qty btn btn-black rounded-0"
                                        data-item_id="{{ product.id }}" id="decrement-qty_{{ product.id }}">
                                        <span class="icon">
                                            <i class="fas fa-minus"></i>
                                        </span>
                                    </button>
                                </div>
                                <input class="form-control qty_input" type="number" name="quantity" value="1" min="1"
                                    max="99" data-item_id="{{ product.id }}" id="id_qty_{{ product.id }}">
                                <div class="input-group-append">
                                    <button class="increment-qty btn btn-black rounded-0"
                                        data-item_id="{{ product.id }}" id="increment-qty_{{ product.id }}">
                                        <span class="icon">
                                            <i class="fas fa-plus"></i>
                                        </span>
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col{% if s %}-12 mt-2{% endif %}">
                        <a href="{% url 'products' %}" class="btn btn-outline-black rounded-0 mt-5">
                            <span class="icon">
                                <i class="fas fa-chevron-left text-white"></i>
                            </span>
                            <span class="text-uppercase text-black">Keep Shopping</span>
                        </a>
                        <input type="submit" class="btn btn-black rounded-0 text-uppercase mt-5" value="Add to Bag">
                    </div>
                    <input type="hidden" name="redirect_url" value="{{ request.path }}">
                    {% endwith %}
                </form>
            </div>
        </div>
    </section>
    <!-- Product Review section -->
    <section class="reveiw">
        <div class="row review-page-heading container-fluid">
            <div class="col-12">
                <h4 class="text-uppercase text-black">Reviews</h4>
                <hr>
            </div>
        </div>
        <div class="row review-page-body container">
            <div class="col-md-6 col-12 added-review-container">
                {% for review in product.reviews.all %}
                <div class="review-info mt-3">
                    <span class="text-black review-user-i">BY {{ review.user}}</span>
                    <span class="text-black review-user-date">ON THE: {{ review.created_on|date:"d-m-Y"}} <span>
                            <br>
                            <p class="text-black">Rating on this product: <span
                                    class="text-black review-user-rating">{{ review.review_rating }} stars</span></p>
                </div>
                <div class="review-comment mt-1">
                    <p class="text-black">{{ review.comment }}</p>
                </div>
                <div class="review-delete-comment">
                    {% if request.user.is_superuser %}
                    <a class=" text-danger text-decoration-none" href="{% url 'delete_review' review.id %}"><i
                            class="fas fa-trash-alt"></i> Click to delete
                        Review</a>
                    {% endif %}
                </div>
                <hr>
                {% endfor%}
            </div>
            <div class="col-md-6 col-12 text-center">
                <div class="review-form-heading">
                    <h5 class="text-uppercase text-black">Write Your Review!</h5>
                </div>
                <div class="review-form-body">
                    {% if request.user.is_authenticated %}
                    <form method="POST" action="{% url 'add_review' product.id %}">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <div class="text-center mt-3">
                            <button class="btn bb1 rounded-0 text-uppercase" type="submit">Submit Review</button>
                        </div>
                    </form>
                    {% else %}
                    <p class="text-black review-text text-center mt-4">
                        To Leave a Review!
                        <a class="user-login" href="{% url 'account_signup' %}">Register</a> or <a class="user-login"
                            href="{% url 'account_login' %}">Log In</a>
                    </p>
                    {% endif %}
                </div>
            </div>
        </div>
    </section>
</div>
{% endblock %}

{% block postloadjs %}
{{ block.super }}
{% include 'products/includes/quantity_input_script.html' %}
{% endblock %}